name: ergo_particle_gym
dependencies:
  - python=3.5.4
  - ipython=6.5.0
  - yaml
  - pip:
    - gym==0.10.5
    - pyyaml
    - matplotlib
    - scipy
    - tensorflow==1.8.0
    - jupyter
    - prompt-toolkit==1.0.15
    - numpy==1.14.5
    - pandas
    - scikit-learn
    - ipdb
    - nose
    - snakeviz
    - shapely
    - joblib
    - opencv-python
    - rq
    - rq-dashboard
